### ISSUE TITLE
keep serverId as default-kieserver when installing on localhost

### ISSUE THREAD

**Issue by rafaeltuelho** [redhat-cop/businessautomation-cop#217] opened 2020-09-08 17:15 UTC
The script uses `remote-kieserver` as the kie-server id in `standalone.xml`... But when you try to deploy a Project from the BC UI it gets deployed in the `default-kieserver`. To get your project deployed to the `remote-kieserver` you have to do it manually from the BC servers UI.

**Comment by erouvas** [comment] 2020-09-08 22:58
Cannot reproduce. Deployments are possible using the BC UI with no manual intervention required.

Steps to reproduce deployment:
- use [pam-eap-setup](https://github.com/redhat-cop/businessautomation-cop/tree/master/pam-eap-setup)
- install RHPAM.7.8.1 BC and KIE nodes by executing `./pam-setup.sh`
- start BC and KIE with `./go_pam.sh`
- login to BC and import psample project from https://gitlab.com/simple-pam-projects/restworkitemhandlerprocess (any project would do, this is just an easy reference)
- while viewing the project's assets, click on "Deploy" button 
- project gets deployed on the `remote-kieserver` KIE Server
- verify by selecting Menu -> Execution Servers

KIE Server id can also be overriden by specifying suitable value for the `org.kie.server.id` parameter in the `pam.config` file before running the `pam-setup.sh` script

**Comment by rafaeltuelho** [comment] 2020-09-09 12:10
@erouvas I'll check this again. I tried with PAM 7.8.0 here and the project gets deployed to `default-kieserver` instead of the `remote-kieserver` which is specified in the `org.kie.server.id`.

**Comment by erouvas** [comment] 2020-09-10 02:14
Tried steps outlined in https://github.com/redhat-cop/businessautomation-cop/issues/217#issuecomment-689179475 with 2 and 3 KIE Server nodes, `-b multi=2` and `-b multi=3` respectively.

Deployment proceeds as expected with the sample project deployed to all KIE Servers with the default `remote-kieserver` ID provided during installation.

Using the UI for examining the deployments the URL to access the KIE Server is only shown for the first node, i.e. the node with the 8080 port. The URL for other nodes is not shown although servers still accessible through regular REST requests.

Using KIE Servers with different KIE Server IDs deployment is still possible with a twist. Using the "Deploy" button from the Business Central UI brings up a dialog that has a server configuration field that should allow for choosing the deployment server. Unfortunately the field is greyed out and server selection is not possible.
Deployment is still possible and it KJAR will be deployed in the first server id available by lexicographical order, i.e. with two server id available `remote-kieserver` and `zemote-kieserver` deployment will select `remote-kieserver`.

**Comment by erouvas** [comment] 2021-06-20 11:10
can we please close this issue?
Cannot be reproduced.

**Comment by ally-jarrett** [comment] 2021-06-20 17:49
Cannot be reproduced.

**Closed by ally-jarrett** 2021-06-20 17:49 UTC
